spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/note_demo_app?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
    username: 'demouser'
    password: 'demouser'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
